### ISSUE TITLE
Setup multiprocessing on tile conversion

### ISSUE THREAD

**Issue by jordancaraballo** [nasa-nccs-hpda/above-shrubs#4]
Setup multiprocessing on tile conversion from the setup step.

**Comment by jordancaraballo** [comment]
Speed up is seen, closing this feature now.

**Comment by mmacander** [comment]
I do see the speed-up, however, the .npy files from training are getting written to both the training and test directory and I do not see the test .npy files being written anywhere.

See example outputs at /explore/nobackup/people/mmacande/srlite/chm_model/20230515d_chm

**Comment by jordancaraballo** [comment]
Feel free to pull the latest version, this should include the fix.
