### ISSUE TITLE
Add DTM layer to the data stack of strips for prediction

### ISSUE THREAD

**Issue by jordancaraballo** [nasa-nccs-hpda/above-shrubs#7]
Add DTM layer to the data stack of strips for prediction. @mmacander can you point me to the script or process you are using to include the DTM layers in the training tiles?

**Comment by mmacander** [comment]
The tiles are generated in R using the function below. The key part for
prediction purposes is that it takes the 5m IFSAR DTM (path below) and
resamples/reprojects it to the extent and pixel size of a 256x256 pixel
SRLite chip using bilinear resampling.

It does the same with the DSM and calculates the CHM as DSM - DTM.

It adds the DTM as the fifth band to the 4-band SRLite.

It takes the CHM and clamps so the minimum value is 0.0000001 (this is how
I fixed the dumb -0 problem when it recurred).

Then it converts to decimeters and rounds.

Finally it checks to make sure that some non-zero values occur in the CHM
label chip. When I had about 70 out of 29k tiles that were 100% zero the
model gradients exploded to NANs.

Anyway for prediction I think we can accomplish the step of adding the DTM
band by getting the CRS and bounds of each SRLite scene; using gdalwarp or
similar command to resample/reproject the DTM to the correct
footprint/resolution (with bilinear); then add the DTM band to the stack.
It could probably be done on-the-fly for each SRLite scene
during predict (assuming we don't want to create another bigger copy of
each SRLite scene on disk). There is definitely some code that did similar
things from the SRLite evaluation notebooks.



ifsar_dtm <-
> rast('/explore/nobackup/projects/dem/AK_IFSAR/alaska_ifsar_dtm_20221222.tif')
> ifsar_dsm <-
> rast('/explore/nobackup/projects/dem/AK_IFSAR/alaska_ifsar_dsm_20221222.tif')


crop_by_bbox2_chm <- function(epsg, utmBB, baseName, chipName, outPrefix) {
>
>     sr_2m_strip <- rast(path(alaska_2m, glue('{baseName}-sr-02m.tif')))
>
>     sr_2m <- crop(sr_2m_strip, utmBB)#, filename=path(outPath,
> glue('{epsg}_{long}_{lat}.tif')))
>
>     names(sr_2m) <- c('01_blue','02_green','03_red','04_nir')
>
>     dtm_2m <- project(ifsar_dtm, sr_2m, method='bilinear')
>
>     dsm_2m <- project(ifsar_dsm, sr_2m, method='bilinear')
>
>     chm_2m <- dsm_2m - dtm_2m
>
>     chm_2m_clamp <- clamp(chm_2m, 0.0000001, 10000)
>
>     chm_dm_2m <- round(chm_2m_clamp * 10)
>
>
>
>     names(dtm_2m) <- c('05_dtm_m')
>
>     names(chm_2m) <- c('06_chm_m')
>
>     chm_sum = global(chm_dm_2m, 'sum')[[1]]
>
>     if(chm_sum > 0) {
>
>         predictor_stack_2m <- c(sr_2m, dtm_2m)
>
>         writeRaster(predictor_stack_2m, filename=path(outPath,
> glue('{outPrefix}_images'), glue('{chipName}.tif')), overwrite=T)
>
>         label_stack_2m <- c(chm_dm_2m)
>
>         writeRaster(label_stack_2m, filename=path(outPath,
> glue('{outPrefix}_labels'), glue('{chipName}.tif')), overwrite=T)
>
>         } else {
>
>         print(glue('{chipName} is all zero canopy height, not exported')) }
>
>     return(baseName)
> }


Matt Macander
<http://www.abrinc.com/about/offices/fairbanks/matthew-j-macander-ms/>  |
Senior Scientist
ABR, Inc.—Environmental Research & Services
P.O. Box 80410  |  Fairbanks, AK 99708
907-455-6777 ext. 112 |  ***@***.*** | c. 907-347-7041
